name: benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run:  git submodule update --init
    - name: make
      run:  make
    - name: benchmark
      run:  ./examples/benchmark
    - name: make clean
      run:  make clean
